# Celery 的broker配置。存储ft指令执行结果。
# 密码加密规则和backend一致, 暂不支持集群redis
redis_url: "redis://:gAAAAABl0cIKZe2XooAzwuWgq1Ai26_Th4TDvbKDJ-1Jap1CGaiotQb7HyF-iG7-ksJe3B8rtQQCztAddTJHoBpUB2PiUgvlOg==@bisheng-redis:6379/5"
